# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Asitha Nanayakkara
tagline:             'res ipsa loquitur'
description:         'Here I share my thoughts, findings and anything that interests me.<br/><i>Cheers!</i>'
url:                 asitha.github.io
baseurl:             /
paginate:            5

avatar: https://avatars0.githubusercontent.com/u/919462?v=3&s=140

# Your disqus shortname, entering this will enable commenting on posts
disqus: asithan

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-57023311-1

github: https://github.com/Asitha/

# About/contact
author:
  name:              Asitha Nanayakkara
  url:               https://twitter.com/sharaqzion
  email:             dulanjana.asitha@gmail.com

# Use the following plug-ins
# gems:
#   - jemoji # Emoji please!
#   - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem

# Exclude these files from your production _site
# exclude:
#     - Gemfile
#     - Gemfile.lock
#     - LICENSE
#     - README.md

# Custom vars
version:             1.0.0
